version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: weather_postgres
    environment:
      POSTGRES_DB: weather_readings
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  python-app:
    build: .
    container_name: weather_pipeline
    depends_on:
      - postgres
    volumes:
      - .:/app
    working_dir: /app
    command: bash docker/entrypoint.sh

volumes:
  pgdata: